utilisateurs:
    resource: "@utilisateursBundle/Resources/config/routing.yml"
    prefix:   /

crowd_rise:
    resource: "@CrowdRiseBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
# app/config/routing.yml
