crowd_rise_homepage:
    path:     /hello/{name}
    defaults: { _controller: CrowdRiseBundle:Default:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: CrowdRiseBundle:Crowd:acceuil }
freelancer:
    path:     /freelancer
    defaults: { _controller: CrowdRiseBundle:Crowd:freelancer }
Calendrier_evenements:
    path:     /Calendrier_evenements
    defaults: { _controller: CrowdRiseBundle:Crowd:Calendrier_evenements }
detail_evenement:
    path:     /detail_evenement
    defaults: { _controller: CrowdRiseBundle:Crowd:detail_evenement }
evenement_avenir:
    path:     /evenement_avenir
    defaults: { _controller: CrowdRiseBundle:Crowd:evenement_avenir }

List_projets:
    path:     /List_projets
    defaults: { _controller: CrowdRiseBundle:Crowd:List_projets }
detail_projets:
    path:     /detail_projets
    defaults: { _controller: CrowdRiseBundle:Crowd:detail_projets }
financement_projets:
    path:     /financement_projets
    defaults: { _controller: CrowdRiseBundle:Crowd:financement_projets }
contact:
    path:     /contact
    defaults: { _controller: CrowdRiseBundle:Crowd:contact }
login:
    path:     /login
    defaults: { _controller: CrowdRiseBundle:Crowd:login }
publier_projet:
    path:   /publier_projet
    defaults: { _controller: CrowdRiseBundle:Crowd:publier_projet }
connecte:
    path:   /connecte
    defaults: { _controller: CrowdRiseBundle:Crowd:connecte }
