services:
#    crowd_rise.example:
#        class: Crowd\CrowdRiseBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    fos_user.doctrine_registry:
        alias: doctrine